### ISSUE TITLE
Error while compiling font.

### ISSUE THREAD

**Issue by ygalanter** [jrmobley/pebble-fctx-compiler#1]
Not sure if I am doing something wrong or the fact that I am running Node on Windows has something to do with it, but when I am trying to compile a font, getting this:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'charCodeAt' of undefined
    at C:\Temp\fctx-compiler.js:111:31
    at Array.reduce (native)
    at packFont (C:\Temp\fctx-compiler.js:108:34)
    at C:\Temp\fctx-compiler.js:56:30
    at Function._.each._.forEach (C:\Temp\node_modules\underscore\underscore.js:153:9)
    at C:\Temp\fctx-compiler.js:54:11
    at Parser.<anonymous> (C:\Temp\node_modules\xml2js\lib\xml2js.js:483:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.onclosetag (C:\Temp\node_modules\xml2js\lib\xml2js.js:444:26)
```

Font originally was a TTF, converted it to SVG via FontForge. Any help is appreciated. Thanks!

**Comment by jrmobley** [comment]
Just looking at the call stack, it suggests that one of the `<glyph>` tags is missing its `unicode` param.  You might scan through your SVG for any odd glyphs.

**Comment by ygalanter** [comment]
That was it! Thank you. And thank you for the cool Pebble graphics library!
